using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace NewsFlow.Infrastructure.Persistence.Migrations
{
    /// <inheritdoc />
    public partial class SeedReferenceData : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // ── Roles ──────────────────────────────────────────────
            migrationBuilder.Sql(@"
INSERT INTO roles (""Id"", ""Name"", ""Description"", ""CreatedAt"") VALUES
('10000000-0000-0000-0000-000000000001', 'Administrator', 'Управление пользователями, справочниками, конфигурацией', NOW()),
('10000000-0000-0000-0000-000000000002', 'Operator',      'Загрузка и первичная разметка материалов', NOW()),
('10000000-0000-0000-0000-000000000003', 'Translator',    'Перевод иноязычных материалов', NOW()),
('10000000-0000-0000-0000-000000000004', 'Analyst',       'Анализ материалов и подготовка документов', NOW()),
('10000000-0000-0000-0000-000000000005', 'Reviewer',      'Проверка качества документов', NOW()),
('10000000-0000-0000-0000-000000000006', 'Registrar',     'Регистрация и присвоение номеров документам', NOW()),
('10000000-0000-0000-0000-000000000007', 'Controller',    'Финальный контроль и оценка документов', NOW()),
('10000000-0000-0000-0000-000000000008', 'Evaluator',     'Оценка документов', NOW())
ON CONFLICT (""Name"") DO NOTHING;
");

            // ── Languages (ISO 639-1) ──────────────────────────────
            migrationBuilder.Sql(@"
INSERT INTO languages (""Id"", ""Code"", ""Name"", ""CreatedAt"") VALUES
(gen_random_uuid(), 'ru', 'Русский', NOW()),
(gen_random_uuid(), 'en', 'Английский', NOW()),
(gen_random_uuid(), 'ar', 'Арабский', NOW()),
(gen_random_uuid(), 'zh', 'Китайский', NOW()),
(gen_random_uuid(), 'fr', 'Французский', NOW()),
(gen_random_uuid(), 'de', 'Немецкий', NOW()),
(gen_random_uuid(), 'es', 'Испанский', NOW()),
(gen_random_uuid(), 'pt', 'Португальский', NOW()),
(gen_random_uuid(), 'ja', 'Японский', NOW()),
(gen_random_uuid(), 'ko', 'Корейский', NOW()),
(gen_random_uuid(), 'tr', 'Турецкий', NOW()),
(gen_random_uuid(), 'fa', 'Персидский', NOW()),
(gen_random_uuid(), 'hi', 'Хинди', NOW()),
(gen_random_uuid(), 'ur', 'Урду', NOW()),
(gen_random_uuid(), 'it', 'Итальянский', NOW()),
(gen_random_uuid(), 'pl', 'Польский', NOW()),
(gen_random_uuid(), 'uk', 'Украинский', NOW()),
(gen_random_uuid(), 'he', 'Иврит', NOW()),
(gen_random_uuid(), 'sv', 'Шведский', NOW()),
(gen_random_uuid(), 'nl', 'Нидерландский', NOW()),
(gen_random_uuid(), 'cs', 'Чешский', NOW()),
(gen_random_uuid(), 'ro', 'Румынский', NOW()),
(gen_random_uuid(), 'hu', 'Венгерский', NOW()),
(gen_random_uuid(), 'el', 'Греческий', NOW()),
(gen_random_uuid(), 'bg', 'Болгарский', NOW()),
(gen_random_uuid(), 'sr', 'Сербский', NOW()),
(gen_random_uuid(), 'th', 'Тайский', NOW()),
(gen_random_uuid(), 'vi', 'Вьетнамский', NOW()),
(gen_random_uuid(), 'id', 'Индонезийский', NOW()),
(gen_random_uuid(), 'ms', 'Малайский', NOW()),
(gen_random_uuid(), 'da', 'Датский', NOW()),
(gen_random_uuid(), 'fi', 'Финский', NOW()),
(gen_random_uuid(), 'no', 'Норвежский', NOW()),
(gen_random_uuid(), 'sk', 'Словацкий', NOW()),
(gen_random_uuid(), 'sl', 'Словенский', NOW()),
(gen_random_uuid(), 'hr', 'Хорватский', NOW()),
(gen_random_uuid(), 'lt', 'Литовский', NOW()),
(gen_random_uuid(), 'lv', 'Латышский', NOW()),
(gen_random_uuid(), 'et', 'Эстонский', NOW()),
(gen_random_uuid(), 'ka', 'Грузинский', NOW()),
(gen_random_uuid(), 'hy', 'Армянский', NOW()),
(gen_random_uuid(), 'az', 'Азербайджанский', NOW()),
(gen_random_uuid(), 'kk', 'Казахский', NOW()),
(gen_random_uuid(), 'uz', 'Узбекский', NOW()),
(gen_random_uuid(), 'tg', 'Таджикский', NOW()),
(gen_random_uuid(), 'ky', 'Киргизский', NOW()),
(gen_random_uuid(), 'tk', 'Туркменский', NOW()),
(gen_random_uuid(), 'mn', 'Монгольский', NOW()),
(gen_random_uuid(), 'ps', 'Пушту', NOW()),
(gen_random_uuid(), 'bn', 'Бенгальский', NOW()),
(gen_random_uuid(), 'ta', 'Тамильский', NOW()),
(gen_random_uuid(), 'te', 'Телугу', NOW()),
(gen_random_uuid(), 'ml', 'Малаялам', NOW()),
(gen_random_uuid(), 'sw', 'Суахили', NOW()),
(gen_random_uuid(), 'am', 'Амхарский', NOW()),
(gen_random_uuid(), 'ne', 'Непальский', NOW()),
(gen_random_uuid(), 'si', 'Сингальский', NOW()),
(gen_random_uuid(), 'km', 'Кхмерский', NOW()),
(gen_random_uuid(), 'lo', 'Лаосский', NOW()),
(gen_random_uuid(), 'my', 'Бирманский', NOW())
ON CONFLICT (""Code"") DO NOTHING;
");

            // ── Sources ────────────────────────────────────────────
            migrationBuilder.Sql(@"
INSERT INTO sources (""Id"", ""Name"", ""Description"", ""Type"", ""CreatedAt"") VALUES
(gen_random_uuid(), 'Reuters',        'Информационное агентство Reuters',           'Агентство', NOW()),
(gen_random_uuid(), 'BBC',            'Британская вещательная корпорация',          'СМИ',       NOW()),
(gen_random_uuid(), 'Al Jazeera',     'Катарская медиакомпания',                    'СМИ',       NOW()),
(gen_random_uuid(), 'Xinhua',         'Информационное агентство Синьхуа',           'Агентство', NOW()),
(gen_random_uuid(), 'ТАСС',           'Российское информационное агентство',        'Агентство', NOW()),
(gen_random_uuid(), 'AFP',            'Agence France-Presse',                       'Агентство', NOW()),
(gen_random_uuid(), 'AP',             'Associated Press',                           'Агентство', NOW()),
(gen_random_uuid(), 'DPA',            'Deutsche Presse-Agentur',                    'Агентство', NOW()),
(gen_random_uuid(), 'ANSA',           'Agenzia Nazionale Stampa Associata',         'Агентство', NOW()),
(gen_random_uuid(), 'EFE',            'Agencia EFE (Испания)',                      'Агентство', NOW()),
(gen_random_uuid(), 'Yonhap',         'Информационное агентство Yonhap (Корея)',    'Агентство', NOW()),
(gen_random_uuid(), 'Kyodo',          'Информационное агентство Kyodo (Япония)',    'Агентство', NOW()),
(gen_random_uuid(), 'РИА Новости',    'Российское информационное агентство',        'Агентство', NOW()),
(gen_random_uuid(), 'Интерфакс',      'Информационное агентство Интерфакс',         'Агентство', NOW()),
(gen_random_uuid(), 'CNN',            'Cable News Network',                         'СМИ',       NOW()),
(gen_random_uuid(), 'The Guardian',   'Британская газета',                          'СМИ',       NOW()),
(gen_random_uuid(), 'Le Monde',       'Французская газета',                         'СМИ',       NOW()),
(gen_random_uuid(), 'Der Spiegel',    'Немецкий журнал',                            'СМИ',       NOW()),
(gen_random_uuid(), 'NHK',            'Японская общественная телекомпания',         'СМИ',       NOW()),
(gen_random_uuid(), 'CGTN',           'Китайская глобальная телесеть',              'СМИ',       NOW()),
(gen_random_uuid(), 'France 24',      'Французский международный телеканал',        'СМИ',       NOW()),
(gen_random_uuid(), 'Deutsche Welle', 'Немецкая международная медиакомпания',       'СМИ',       NOW()),
(gen_random_uuid(), 'RT',             'Russia Today',                               'СМИ',       NOW()),
(gen_random_uuid(), 'TRT World',      'Турецкий международный телеканал',           'СМИ',       NOW()),
(gen_random_uuid(), 'Anadolu',        'Информационное агентство Анадолу (Турция)',  'Агентство', NOW()),
(gen_random_uuid(), 'IRNA',           'Информационное агентство IRNA (Иран)',       'Агентство', NOW()),
(gen_random_uuid(), 'WAFA',           'Палестинское информационное агентство',       'Агентство', NOW()),
(gen_random_uuid(), 'SANA',           'Сирийское информационное агентство',          'Агентство', NOW()),
(gen_random_uuid(), 'SPA',            'Саудовское информационное агентство',         'Агентство', NOW()),
(gen_random_uuid(), 'WAM',            'Информационное агентство ОАЭ',               'Агентство', NOW())
ON CONFLICT (""Name"") DO NOTHING;
");

            // ── Tags ───────────────────────────────────────────────
            migrationBuilder.Sql(@"
INSERT INTO tags (""Id"", ""Name"", ""Category"", ""CreatedAt"") VALUES
(gen_random_uuid(), 'Политика',             'Тема',    NOW()),
(gen_random_uuid(), 'Экономика',            'Тема',    NOW()),
(gen_random_uuid(), 'Безопасность',         'Тема',    NOW()),
(gen_random_uuid(), 'Военные действия',     'Тема',    NOW()),
(gen_random_uuid(), 'Дипломатия',           'Тема',    NOW()),
(gen_random_uuid(), 'Терроризм',            'Тема',    NOW()),
(gen_random_uuid(), 'Энергетика',           'Тема',    NOW()),
(gen_random_uuid(), 'Технологии',           'Тема',    NOW()),
(gen_random_uuid(), 'Санкции',              'Тема',    NOW()),
(gen_random_uuid(), 'Торговля',             'Тема',    NOW()),
(gen_random_uuid(), 'Миграция',             'Тема',    NOW()),
(gen_random_uuid(), 'Экология',             'Тема',    NOW()),
(gen_random_uuid(), 'Здравоохранение',      'Тема',    NOW()),
(gen_random_uuid(), 'Образование',          'Тема',    NOW()),
(gen_random_uuid(), 'Культура',             'Тема',    NOW()),
(gen_random_uuid(), 'Спорт',               'Тема',    NOW()),
(gen_random_uuid(), 'Ближний Восток',       'Регион',  NOW()),
(gen_random_uuid(), 'Центральная Азия',     'Регион',  NOW()),
(gen_random_uuid(), 'Юго-Восточная Азия',   'Регион',  NOW()),
(gen_random_uuid(), 'Восточная Азия',       'Регион',  NOW()),
(gen_random_uuid(), 'Европа',              'Регион',  NOW()),
(gen_random_uuid(), 'Северная Америка',     'Регион',  NOW()),
(gen_random_uuid(), 'Латинская Америка',    'Регион',  NOW()),
(gen_random_uuid(), 'Африка',              'Регион',  NOW()),
(gen_random_uuid(), 'СНГ',                 'Регион',  NOW()),
(gen_random_uuid(), 'Арктика',             'Регион',  NOW()),
(gen_random_uuid(), 'Срочно',              'Приоритет', NOW()),
(gen_random_uuid(), 'Важно',               'Приоритет', NOW()),
(gen_random_uuid(), 'Эксклюзив',           'Приоритет', NOW())
ON CONFLICT (""Name"") DO NOTHING;
");

            // ── Countries (ISO 3166-1 alpha-2) ─────────────────────
            migrationBuilder.Sql(@"
INSERT INTO countries (""Id"", ""Code"", ""Name"", ""CreatedAt"") VALUES
(gen_random_uuid(), 'AF', 'Афганистан', NOW()),
(gen_random_uuid(), 'AL', 'Албания', NOW()),
(gen_random_uuid(), 'DZ', 'Алжир', NOW()),
(gen_random_uuid(), 'AS', 'Американское Самоа', NOW()),
(gen_random_uuid(), 'AD', 'Андорра', NOW()),
(gen_random_uuid(), 'AO', 'Ангола', NOW()),
(gen_random_uuid(), 'AI', 'Ангилья', NOW()),
(gen_random_uuid(), 'AQ', 'Антарктида', NOW()),
(gen_random_uuid(), 'AG', 'Антигуа и Барбуда', NOW()),
(gen_random_uuid(), 'AR', 'Аргентина', NOW()),
(gen_random_uuid(), 'AM', 'Армения', NOW()),
(gen_random_uuid(), 'AW', 'Аруба', NOW()),
(gen_random_uuid(), 'AU', 'Австралия', NOW()),
(gen_random_uuid(), 'AT', 'Австрия', NOW()),
(gen_random_uuid(), 'AZ', 'Азербайджан', NOW()),
(gen_random_uuid(), 'BS', 'Багамы', NOW()),
(gen_random_uuid(), 'BH', 'Бахрейн', NOW()),
(gen_random_uuid(), 'BD', 'Бангладеш', NOW()),
(gen_random_uuid(), 'BB', 'Барбадос', NOW()),
(gen_random_uuid(), 'BY', 'Беларусь', NOW()),
(gen_random_uuid(), 'BE', 'Бельгия', NOW()),
(gen_random_uuid(), 'BZ', 'Белиз', NOW()),
(gen_random_uuid(), 'BJ', 'Бенин', NOW()),
(gen_random_uuid(), 'BM', 'Бермуды', NOW()),
(gen_random_uuid(), 'BT', 'Бутан', NOW()),
(gen_random_uuid(), 'BO', 'Боливия', NOW()),
(gen_random_uuid(), 'BQ', 'Бонэйр, Синт-Эстатиус и Саба', NOW()),
(gen_random_uuid(), 'BA', 'Босния и Герцеговина', NOW()),
(gen_random_uuid(), 'BW', 'Ботсвана', NOW()),
(gen_random_uuid(), 'BV', 'Остров Буве', NOW()),
(gen_random_uuid(), 'BR', 'Бразилия', NOW()),
(gen_random_uuid(), 'IO', 'Британская территория в Индийском океане', NOW()),
(gen_random_uuid(), 'BN', 'Бруней', NOW()),
(gen_random_uuid(), 'BG', 'Болгария', NOW()),
(gen_random_uuid(), 'BF', 'Буркина-Фасо', NOW()),
(gen_random_uuid(), 'BI', 'Бурунди', NOW()),
(gen_random_uuid(), 'CV', 'Кабо-Верде', NOW()),
(gen_random_uuid(), 'KH', 'Камбоджа', NOW()),
(gen_random_uuid(), 'CM', 'Камерун', NOW()),
(gen_random_uuid(), 'CA', 'Канада', NOW()),
(gen_random_uuid(), 'KY', 'Каймановы острова', NOW()),
(gen_random_uuid(), 'CF', 'Центральноафриканская Республика', NOW()),
(gen_random_uuid(), 'TD', 'Чад', NOW()),
(gen_random_uuid(), 'CL', 'Чили', NOW()),
(gen_random_uuid(), 'CN', 'Китай', NOW()),
(gen_random_uuid(), 'CX', 'Остров Рождества', NOW()),
(gen_random_uuid(), 'CC', 'Кокосовые острова', NOW()),
(gen_random_uuid(), 'CO', 'Колумбия', NOW()),
(gen_random_uuid(), 'KM', 'Коморы', NOW()),
(gen_random_uuid(), 'CG', 'Конго', NOW()),
(gen_random_uuid(), 'CD', 'ДР Конго', NOW()),
(gen_random_uuid(), 'CK', 'Острова Кука', NOW()),
(gen_random_uuid(), 'CR', 'Коста-Рика', NOW()),
(gen_random_uuid(), 'HR', 'Хорватия', NOW()),
(gen_random_uuid(), 'CU', 'Куба', NOW()),
(gen_random_uuid(), 'CW', 'Кюрасао', NOW()),
(gen_random_uuid(), 'CY', 'Кипр', NOW()),
(gen_random_uuid(), 'CZ', 'Чехия', NOW()),
(gen_random_uuid(), 'CI', 'Кот-д''Ивуар', NOW()),
(gen_random_uuid(), 'DK', 'Дания', NOW()),
(gen_random_uuid(), 'DJ', 'Джибути', NOW()),
(gen_random_uuid(), 'DM', 'Доминика', NOW()),
(gen_random_uuid(), 'DO', 'Доминиканская Республика', NOW()),
(gen_random_uuid(), 'EC', 'Эквадор', NOW()),
(gen_random_uuid(), 'EG', 'Египет', NOW()),
(gen_random_uuid(), 'SV', 'Сальвадор', NOW()),
(gen_random_uuid(), 'GQ', 'Экваториальная Гвинея', NOW()),
(gen_random_uuid(), 'ER', 'Эритрея', NOW()),
(gen_random_uuid(), 'EE', 'Эстония', NOW()),
(gen_random_uuid(), 'SZ', 'Эсватини', NOW()),
(gen_random_uuid(), 'ET', 'Эфиопия', NOW()),
(gen_random_uuid(), 'FK', 'Фолклендские острова', NOW()),
(gen_random_uuid(), 'FO', 'Фарерские острова', NOW()),
(gen_random_uuid(), 'FJ', 'Фиджи', NOW()),
(gen_random_uuid(), 'FI', 'Финляндия', NOW()),
(gen_random_uuid(), 'FR', 'Франция', NOW()),
(gen_random_uuid(), 'GF', 'Французская Гвиана', NOW()),
(gen_random_uuid(), 'PF', 'Французская Полинезия', NOW()),
(gen_random_uuid(), 'TF', 'Французские Южные территории', NOW()),
(gen_random_uuid(), 'GA', 'Габон', NOW()),
(gen_random_uuid(), 'GM', 'Гамбия', NOW()),
(gen_random_uuid(), 'GE', 'Грузия', NOW()),
(gen_random_uuid(), 'DE', 'Германия', NOW()),
(gen_random_uuid(), 'GH', 'Гана', NOW()),
(gen_random_uuid(), 'GI', 'Гибралтар', NOW()),
(gen_random_uuid(), 'GR', 'Греция', NOW()),
(gen_random_uuid(), 'GL', 'Гренландия', NOW()),
(gen_random_uuid(), 'GD', 'Гренада', NOW()),
(gen_random_uuid(), 'GP', 'Гваделупа', NOW()),
(gen_random_uuid(), 'GU', 'Гуам', NOW()),
(gen_random_uuid(), 'GT', 'Гватемала', NOW()),
(gen_random_uuid(), 'GG', 'Гернси', NOW()),
(gen_random_uuid(), 'GN', 'Гвинея', NOW()),
(gen_random_uuid(), 'GW', 'Гвинея-Бисау', NOW()),
(gen_random_uuid(), 'GY', 'Гайана', NOW()),
(gen_random_uuid(), 'HT', 'Гаити', NOW()),
(gen_random_uuid(), 'HM', 'Херд и Макдональд', NOW()),
(gen_random_uuid(), 'VA', 'Ватикан', NOW()),
(gen_random_uuid(), 'HN', 'Гондурас', NOW()),
(gen_random_uuid(), 'HK', 'Гонконг', NOW()),
(gen_random_uuid(), 'HU', 'Венгрия', NOW()),
(gen_random_uuid(), 'IS', 'Исландия', NOW()),
(gen_random_uuid(), 'IN', 'Индия', NOW()),
(gen_random_uuid(), 'ID', 'Индонезия', NOW()),
(gen_random_uuid(), 'IR', 'Иран', NOW()),
(gen_random_uuid(), 'IQ', 'Ирак', NOW()),
(gen_random_uuid(), 'IE', 'Ирландия', NOW()),
(gen_random_uuid(), 'IM', 'Остров Мэн', NOW()),
(gen_random_uuid(), 'IL', 'Израиль', NOW()),
(gen_random_uuid(), 'IT', 'Италия', NOW()),
(gen_random_uuid(), 'JM', 'Ямайка', NOW()),
(gen_random_uuid(), 'JP', 'Япония', NOW()),
(gen_random_uuid(), 'JE', 'Джерси', NOW()),
(gen_random_uuid(), 'JO', 'Иордания', NOW()),
(gen_random_uuid(), 'KZ', 'Казахстан', NOW()),
(gen_random_uuid(), 'KE', 'Кения', NOW()),
(gen_random_uuid(), 'KI', 'Кирибати', NOW()),
(gen_random_uuid(), 'KP', 'КНДР', NOW()),
(gen_random_uuid(), 'KR', 'Республика Корея', NOW()),
(gen_random_uuid(), 'KW', 'Кувейт', NOW()),
(gen_random_uuid(), 'KG', 'Киргизия', NOW()),
(gen_random_uuid(), 'LA', 'Лаос', NOW()),
(gen_random_uuid(), 'LV', 'Латвия', NOW()),
(gen_random_uuid(), 'LB', 'Ливан', NOW()),
(gen_random_uuid(), 'LS', 'Лесото', NOW()),
(gen_random_uuid(), 'LR', 'Либерия', NOW()),
(gen_random_uuid(), 'LY', 'Ливия', NOW()),
(gen_random_uuid(), 'LI', 'Лихтенштейн', NOW()),
(gen_random_uuid(), 'LT', 'Литва', NOW()),
(gen_random_uuid(), 'LU', 'Люксембург', NOW()),
(gen_random_uuid(), 'MO', 'Макао', NOW()),
(gen_random_uuid(), 'MG', 'Мадагаскар', NOW()),
(gen_random_uuid(), 'MW', 'Малави', NOW()),
(gen_random_uuid(), 'MY', 'Малайзия', NOW()),
(gen_random_uuid(), 'MV', 'Мальдивы', NOW()),
(gen_random_uuid(), 'ML', 'Мали', NOW()),
(gen_random_uuid(), 'MT', 'Мальта', NOW()),
(gen_random_uuid(), 'MH', 'Маршалловы Острова', NOW()),
(gen_random_uuid(), 'MQ', 'Мартиника', NOW()),
(gen_random_uuid(), 'MR', 'Мавритания', NOW()),
(gen_random_uuid(), 'MU', 'Маврикий', NOW()),
(gen_random_uuid(), 'YT', 'Майотта', NOW()),
(gen_random_uuid(), 'MX', 'Мексика', NOW()),
(gen_random_uuid(), 'FM', 'Микронезия', NOW()),
(gen_random_uuid(), 'MD', 'Молдова', NOW()),
(gen_random_uuid(), 'MC', 'Монако', NOW()),
(gen_random_uuid(), 'MN', 'Монголия', NOW()),
(gen_random_uuid(), 'ME', 'Черногория', NOW()),
(gen_random_uuid(), 'MS', 'Монтсеррат', NOW()),
(gen_random_uuid(), 'MA', 'Марокко', NOW()),
(gen_random_uuid(), 'MZ', 'Мозамбик', NOW()),
(gen_random_uuid(), 'MM', 'Мьянма', NOW()),
(gen_random_uuid(), 'NA', 'Намибия', NOW()),
(gen_random_uuid(), 'NR', 'Науру', NOW()),
(gen_random_uuid(), 'NP', 'Непал', NOW()),
(gen_random_uuid(), 'NL', 'Нидерланды', NOW()),
(gen_random_uuid(), 'NC', 'Новая Каледония', NOW()),
(gen_random_uuid(), 'NZ', 'Новая Зеландия', NOW()),
(gen_random_uuid(), 'NI', 'Никарагуа', NOW()),
(gen_random_uuid(), 'NE', 'Нигер', NOW()),
(gen_random_uuid(), 'NG', 'Нигерия', NOW()),
(gen_random_uuid(), 'NU', 'Ниуэ', NOW()),
(gen_random_uuid(), 'NF', 'Остров Норфолк', NOW()),
(gen_random_uuid(), 'MK', 'Северная Македония', NOW()),
(gen_random_uuid(), 'MP', 'Северные Марианские острова', NOW()),
(gen_random_uuid(), 'NO', 'Норвегия', NOW()),
(gen_random_uuid(), 'OM', 'Оман', NOW()),
(gen_random_uuid(), 'PK', 'Пакистан', NOW()),
(gen_random_uuid(), 'PW', 'Палау', NOW()),
(gen_random_uuid(), 'PS', 'Палестина', NOW()),
(gen_random_uuid(), 'PA', 'Панама', NOW()),
(gen_random_uuid(), 'PG', 'Папуа — Новая Гвинея', NOW()),
(gen_random_uuid(), 'PY', 'Парагвай', NOW()),
(gen_random_uuid(), 'PE', 'Перу', NOW()),
(gen_random_uuid(), 'PH', 'Филиппины', NOW()),
(gen_random_uuid(), 'PN', 'Острова Питкэрн', NOW()),
(gen_random_uuid(), 'PL', 'Польша', NOW()),
(gen_random_uuid(), 'PT', 'Португалия', NOW()),
(gen_random_uuid(), 'PR', 'Пуэрто-Рико', NOW()),
(gen_random_uuid(), 'QA', 'Катар', NOW()),
(gen_random_uuid(), 'RO', 'Румыния', NOW()),
(gen_random_uuid(), 'RU', 'Россия', NOW()),
(gen_random_uuid(), 'RW', 'Руанда', NOW()),
(gen_random_uuid(), 'RE', 'Реюньон', NOW()),
(gen_random_uuid(), 'BL', 'Сен-Бартелеми', NOW()),
(gen_random_uuid(), 'SH', 'Острова Святой Елены', NOW()),
(gen_random_uuid(), 'KN', 'Сент-Китс и Невис', NOW()),
(gen_random_uuid(), 'LC', 'Сент-Люсия', NOW()),
(gen_random_uuid(), 'MF', 'Сен-Мартен', NOW()),
(gen_random_uuid(), 'PM', 'Сен-Пьер и Микелон', NOW()),
(gen_random_uuid(), 'VC', 'Сент-Винсент и Гренадины', NOW()),
(gen_random_uuid(), 'WS', 'Самоа', NOW()),
(gen_random_uuid(), 'SM', 'Сан-Марино', NOW()),
(gen_random_uuid(), 'ST', 'Сан-Томе и Принсипи', NOW()),
(gen_random_uuid(), 'SA', 'Саудовская Аравия', NOW()),
(gen_random_uuid(), 'SN', 'Сенегал', NOW()),
(gen_random_uuid(), 'RS', 'Сербия', NOW()),
(gen_random_uuid(), 'SC', 'Сейшелы', NOW()),
(gen_random_uuid(), 'SL', 'Сьерра-Леоне', NOW()),
(gen_random_uuid(), 'SG', 'Сингапур', NOW()),
(gen_random_uuid(), 'SX', 'Синт-Мартен', NOW()),
(gen_random_uuid(), 'SK', 'Словакия', NOW()),
(gen_random_uuid(), 'SI', 'Словения', NOW()),
(gen_random_uuid(), 'SB', 'Соломоновы Острова', NOW()),
(gen_random_uuid(), 'SO', 'Сомали', NOW()),
(gen_random_uuid(), 'ZA', 'ЮАР', NOW()),
(gen_random_uuid(), 'GS', 'Южная Георгия и Южные Сандвичевы острова', NOW()),
(gen_random_uuid(), 'SS', 'Южный Судан', NOW()),
(gen_random_uuid(), 'ES', 'Испания', NOW()),
(gen_random_uuid(), 'LK', 'Шри-Ланка', NOW()),
(gen_random_uuid(), 'SD', 'Судан', NOW()),
(gen_random_uuid(), 'SR', 'Суринам', NOW()),
(gen_random_uuid(), 'SJ', 'Шпицберген и Ян-Майен', NOW()),
(gen_random_uuid(), 'SE', 'Швеция', NOW()),
(gen_random_uuid(), 'CH', 'Швейцария', NOW()),
(gen_random_uuid(), 'SY', 'Сирия', NOW()),
(gen_random_uuid(), 'TW', 'Тайвань', NOW()),
(gen_random_uuid(), 'TJ', 'Таджикистан', NOW()),
(gen_random_uuid(), 'TZ', 'Танзания', NOW()),
(gen_random_uuid(), 'TH', 'Таиланд', NOW()),
(gen_random_uuid(), 'TL', 'Восточный Тимор', NOW()),
(gen_random_uuid(), 'TG', 'Того', NOW()),
(gen_random_uuid(), 'TK', 'Токелау', NOW()),
(gen_random_uuid(), 'TO', 'Тонга', NOW()),
(gen_random_uuid(), 'TT', 'Тринидад и Тобаго', NOW()),
(gen_random_uuid(), 'TN', 'Тунис', NOW()),
(gen_random_uuid(), 'TR', 'Турция', NOW()),
(gen_random_uuid(), 'TM', 'Туркменистан', NOW()),
(gen_random_uuid(), 'TC', 'Тёркс и Кайкос', NOW()),
(gen_random_uuid(), 'TV', 'Тувалу', NOW()),
(gen_random_uuid(), 'UG', 'Уганда', NOW()),
(gen_random_uuid(), 'UA', 'Украина', NOW()),
(gen_random_uuid(), 'AE', 'ОАЭ', NOW()),
(gen_random_uuid(), 'GB', 'Великобритания', NOW()),
(gen_random_uuid(), 'US', 'США', NOW()),
(gen_random_uuid(), 'UM', 'Малые Тихоокеанские отдалённые острова США', NOW()),
(gen_random_uuid(), 'UY', 'Уругвай', NOW()),
(gen_random_uuid(), 'UZ', 'Узбекистан', NOW()),
(gen_random_uuid(), 'VU', 'Вануату', NOW()),
(gen_random_uuid(), 'VE', 'Венесуэла', NOW()),
(gen_random_uuid(), 'VN', 'Вьетнам', NOW()),
(gen_random_uuid(), 'VG', 'Виргинские острова (Брит.)', NOW()),
(gen_random_uuid(), 'VI', 'Виргинские острова (США)', NOW()),
(gen_random_uuid(), 'WF', 'Уоллис и Футуна', NOW()),
(gen_random_uuid(), 'EH', 'Западная Сахара', NOW()),
(gen_random_uuid(), 'YE', 'Йемен', NOW()),
(gen_random_uuid(), 'ZM', 'Замбия', NOW()),
(gen_random_uuid(), 'ZW', 'Зимбабве', NOW()),
(gen_random_uuid(), 'AX', 'Аландские острова', NOW())
ON CONFLICT (""Code"") DO NOTHING;
");

            // ── Admin user (password: admin123) ────────────────────
            // BCrypt hash pre-computed for 'admin123'
            migrationBuilder.Sql(@"
INSERT INTO users (""Id"", ""Username"", ""PasswordHash"", ""FullName"", ""IsActive"", ""FailedLoginAttempts"", ""CreatedAt"")
VALUES (
    '20000000-0000-0000-0000-000000000001',
    'admin',
    '$2b$11$S4xVMHXUc9dNbCN/FuIJcOE8kP5x9YDYOwz7GaQ2csWImbSi4jilm',
    'Администратор системы',
    true,
    0,
    NOW()
)
ON CONFLICT (""Username"") DO NOTHING;
");

            // ── Link admin to all roles ────────────────────────────
            migrationBuilder.Sql(@"
INSERT INTO user_roles (role_id, user_id)
SELECT r.""Id"", u.""Id""
FROM roles r
CROSS JOIN users u
WHERE u.""Username"" = 'admin'
  AND NOT EXISTS (
    SELECT 1 FROM user_roles ur
    WHERE ur.role_id = r.""Id"" AND ur.user_id = u.""Id""
);
");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"DELETE FROM user_roles WHERE user_id IN (SELECT ""Id"" FROM users WHERE ""Username"" = 'admin');");
            migrationBuilder.Sql(@"DELETE FROM users WHERE ""Username"" = 'admin';");
            migrationBuilder.Sql(@"DELETE FROM tags;");
            migrationBuilder.Sql(@"DELETE FROM sources;");
            migrationBuilder.Sql(@"DELETE FROM countries;");
            migrationBuilder.Sql(@"DELETE FROM languages;");
            migrationBuilder.Sql(@"DELETE FROM roles;");
        }
    }
}
