<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\NewsFlow.Application\NewsFlow.Application.csproj" />
    <ProjectReference Include="..\NewsFlow.Infrastructure\NewsFlow.Infrastructure.csproj" />
    <ProjectReference Include="..\NewsFlow.Infrastructure.Yaml\NewsFlow.Infrastructure.Yaml.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MudBlazor" Version="7.15.0" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
